### ISSUE TITLE
Text to speech not working

### ISSUE THREAD

**Issue by RSiopa** [RSiopa/SAVI_TP1#2]
I tried to put the text to speech the teacher had a link to, however it did not work.
Keeps getting a really big error which after looking at it and debugging for a while, might be because my PC might not have a default driver for it.
If someone can try and uncomment the 3 lines I have for the text to speech to see if it works on another computer, it would be really nice!

**Comment by gilviegas** [comment]
I had the same issue and found out the solution:

In Linux we have to install additional packages fin order to `pyttx3` work.

`pip install pyttsx3`

`sudo apt update && sudo apt install espeak ffmpeg libespea`

[https://pypi.org/project/pyttsx3eaidk/](url)
